/**
 * Precompute System Types
 *
 * Type definitions for the position precomputation system.
 */

import type { EngineAnalysis } from '../types';

/**
 * Next position to precompute
 */
export interface NextPosition {
  fen: string;           // New position FEN
  fromFEN: string;       // Source position FEN
  move: string;          // Move in UCI format
  moveUCI: string;       // UCI: "e2e4"
  moveSAN: string;       // SAN: "e4"
  lineIndex: number;     // Which line (0-4)
  score: number | null;  // Score
  depth: number;         // Tree depth (0=horizontal, 1+=vertical)
}

/**
 * Precompute task
 */
export interface PrecomputeTask {
  id: string;
  cacheKey: string;
  fen: string;
  depth: number;        // Analysis depth (14, 20, etc.)
  multipv: number;      // MultiPV (3, 5, etc.)
  priority: number;     // Priority score

  // Metadata
  fromFEN: string;      // Source position
  move: string;         // Triggering move
  lineIndex: number;    // Which line (0-4)
  treeDepth: number;    // Tree depth (0=horizontal, 1+=vertical)
  createdAt: number;    // Creation timestamp

  // Status
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  retries: number;
  error?: string;
  startedAt?: number;
  completedAt?: number;
}

/**
 * Precompute settings
 */
export interface PrecomputeSettings {
  enabled: boolean;           // Enable/disable
  horizontalDepth: 1 | 3 | 5; // Horizontal: 1/3/5 lines
  verticalDepth: 0 | 1 | 2;   // Vertical: 0/1/2 levels
  delayMs: number;            // Delay before starting (ms)
  maxConcurrent: 1 | 2;       // Max concurrent tasks
}

/**
 * Precompute status
 */
export interface PrecomputeStatus {
  enabled: boolean;
  running: boolean;
  queueSize: number;
  completed: number;
  failed: number;
  cancelled: number;
  currentTask?: {
    move: string;
    lineIndex: number;
    treeDepth: number;
    elapsedMs: number;
  };
}

/**
 * Precompute statistics
 */
export interface PrecomputeStats {
  totalTriggered: number;     // Total triggered
  completed: number;          // Completed count
  failed: number;             // Failed count
  cancelled: number;          // Cancelled count
  cacheHitRate: number;       // Cache hit rate (0-1)
  avgDurationMs: number;      // Average duration (ms)
  totalSavedMs: number;       // Total time saved (ms)

  // Distribution
  horizontalCount: number;    // Horizontal tasks
  verticalCount: number;      // Vertical tasks

  // Last updated
  lastUpdated: number;
}

/**
 * Cached analysis metadata
 */
export interface CachedAnalysisMetadata {
  precomputed: boolean;        // Generated by precompute
  precomputeLevel: number;     // Precompute level (0=user, 1+=auto)
  cachedAt: number;            // Timestamp
  accessCount: number;         // Access count
  lastAccessAt: number;        // Last access time
}

/**
 * Priority levels
 */
export const PRIORITY = {
  USER_MANUAL: 1000,        // User manual request
  HORIZONTAL_1: 100,        // Line 1
  HORIZONTAL_2: 90,         // Line 2
  HORIZONTAL_3: 80,         // Line 3
  HORIZONTAL_4: 70,         // Line 4
  HORIZONTAL_5: 60,         // Line 5
  VERTICAL_DEPTH_1: 50,     // Depth 1
  VERTICAL_DEPTH_2: 40,     // Depth 2
  VERTICAL_DEPTH_3: 30,     // Depth 3
} as const;
