"""Tagger configuration re-exports."""
# Re-export all constants from engine and priorities modules
from .engine import *
from .priorities import *

__all__ = [
    # From engine
    "DEFAULT_STOCKFISH_PATH",
    "DEFAULT_DEPTH",
    "DEFAULT_MULTIPV",
    "CP_THRESHOLD",
    "SMALL_DROP_CP",
    "STYLE_COMPONENT_KEYS",
    "MOBILITY_TOLERANCE",
    "CENTER_TOLERANCE",
    "KING_SAFETY_TOLERANCE",
    "KING_SAFETY_GAIN",
    "MOBILITY_RISK_TRADEOFF",
    "STRUCTURE_THRESHOLD",
    "TACTICAL_THRESHOLD",
    "TACTICAL_DOMINANCE_THRESHOLD",
    "TACTICAL_SLOPE_THRESHOLD",
    "CONTROL_EVAL_DROP",
    "CONTROL_VOLATILITY_DROP_CP",
    "CONTROL_TENSION_DELTA",
    "CONTROL_TENSION_DELTA_ENDGAME",
    "CONTROL_OPP_MOBILITY_DROP",
    "CONTROL_COOLDOWN_PLIES",
    "CONTROL_TACTICAL_WEIGHT_CEILING",
    "CONTROL_PHASE_WEIGHTS",
    "RISK_SMALL_LOSS",
    "INITIATIVE_BOOST",
    "TACTICAL_GAP_FIRST_CHOICE",
    "TACTICAL_MISS_LOSS",
    "TENSION_EVAL_MIN",
    "TENSION_EVAL_MAX",
    "TENSION_SYMMETRY_TOL",
    "NEUTRAL_TENSION_BAND",
    "CONFIG_DIR",
    "THRESHOLDS_FILE",
    # From priorities
    "TAG_PRIORITY",
]
