"""
Tag priority definitions for gating and post-processing.
Lower number = higher priority.
"""

TAG_PRIORITY = {
    "initiative_exploitation": 1,
    "initiative_attempt": 2,
    "file_pressure_c": 3,
    "tension_creation": 4,
    "neutral_tension_creation": 5,
    "premature_attack": 6,
    "constructive_maneuver": 7,
    "constructive_maneuver_prepare": 7,
    "neutral_maneuver": 8,
    "misplaced_maneuver": 9,
    "maneuver_opening": 9,
    "opening_central_pawn_move": 9,
    "opening_rook_pawn_move": 9,
    "tactical_sacrifice": 10,
    "positional_sacrifice": 10,
    "inaccurate_tactical_sacrifice": 11,
    "speculative_sacrifice": 12,
    "desperate_sacrifice": 13,
    "tactical_combination_sacrifice": 14,
    "tactical_initiative_sacrifice": 14,
    "positional_structure_sacrifice": 15,
    "positional_space_sacrifice": 15,
    "prophylactic_move": 10,
    "prophylactic_direct": 10,
    "prophylactic_latent": 11,
    "prophylactic_meaningless": 12,
    "structural_blockage": 13,
    "control_over_dynamics": 14,
    "cod_simplify": 14,
    "cod_plan_kill": 14,
    "cod_freeze_bind": 14,
    "cod_blockade_passed": 14,
    "cod_file_seal": 14,
    "cod_king_safety_shell": 14,
    "cod_space_clamp": 14,
    "cod_regroup_consolidate": 14,
    "cod_slowdown": 14,
    "control_simplify": 15,
    "control_plan_kill": 15,
    "control_freeze_bind": 15,
    "control_blockade_passed": 15,
    "control_file_seal": 15,
    "control_king_safety_shell": 15,
    "control_space_clamp": 15,
    "control_regroup_consolidate": 15,
    "control_slowdown": 15,
    "deferred_initiative": 15,
    "risk_avoidance": 16,
    "structural_compromise_dynamic": 17,
    "structural_compromise_static": 18,
    "structural_integrity": 19,
    "tactical_sensitivity": 20,
    "first_choice": 21,
    "missed_tactic": 22,
    "conversion_precision": 23,
    "panic_move": 24,
    "tactical_recovery": 25,
    "accurate_knight_bishop_exchange": 20,
    "inaccurate_knight_bishop_exchange": 21,
    "bad_knight_bishop_exchange": 22,
    "failed_prophylactic": 12,
}

TENSION_TRIGGER_PRIORITY = {
    "contact_direct": 1,
    "contact_comp": 2,
    "symmetry_core": 3,
    "structural_support": 4,
    "delayed_trend": 5,
}

__all__ = [
    "TAG_PRIORITY",
    "TENSION_TRIGGER_PRIORITY",
]
